@startuml TugasMultithreading
title WhatLyric
package WhatLyric{
  +class WhatLyric.Main{
    +{static}main(args:String[]):void
    -{static}createPlaylist():Playlist
    -{static}createLirikTerimaKasih():List<String>
    -{static}createLirikKicauMania():List<String>
    -{static}createLirikNoBatidao():List<String>
  }
  package Model{
    +class Music{
      -{final}title:String
      -{final}artist:String
      -{final}durationSeconds:int
      -{final}lyrics:List<String>
      +Music(title:String,artist:String,durationSeconds:int,lyrics:List<String>)
      +getTitle():String
      +getArtist():String
      +getDurationSeconds():int
      +getFormattedDuration():String
      +addLyricLine(lyricLine:String):void
      getLyryics():List<String>
      +getLyricsPreview():String
      +toString():String
    }
    +class Playlist{
      -{final}name:String
      -{final}tracks:List<Music>
      -currentTrackIndex:int
      +Playlist(name:String)
      +Playlist(tracks:List<Music>)
      +getName():String
      +addTrack(music:Music):void
      +removeTrack(music:Music):boolean
      +getTrackCount():int
      +getTracks():List<Music>
      +getCurrentTrack():Music
      +nextTrack():Music
      +previousTrack():Music
      +selectTrack(index:int):Music
      +getTotalDurationSeconds():int
      +getFormattedTotalDuration():String
      +toString():String
    }
  }
  package Resource{
    +enum State{
      STOPPED
      PLAYING
      PAUSED
    }
    +class PlayerState{
      -state:State
      -currentMusic:Music
      -currentPositionSeconds:int
      -playlist:Playlist
      -{volatile}running:boolean
      +{synchronized}selectTrack(index:int):void
      +{synchronized}shutdown():void
      +PlayerState()
      +{synchronized}getState():State
      +{synchronized}getCurrentMusic():Music
      +{synchronized}getCurrentPositionSeconds():int
      +{synchronized}getCurrentPositionFormatted():String
      +{synchronized}getPlaylist():Playlist
      +{synchronized}loadPlaylist(playlist:Playlist):void
      +{synchronized}play():void
      +{synchronized}pause():void
      +{synchronized}stop():void
      +{synchronized}seek(seconds:int):void
      +{synchronized}nextTrack():void
      +{synchronized}previousTrack():void
      +{synchronized}tick():void
      +{synchronized}getStatusSummary():String
      +{synchronized}toString():String
    }
  }
  package Thread{
    +class MusicPlayer extends Thread{
      -state:PlayerState
      +MusicPlayer()
      +run():void
    }
    +class LyricDisplayer extends Thread{
      +LyricDisplayer(state:PlayerState)
      -state:PlayerState
      +run():void
      -getLyricAtTime(music:Music,currSecs:int):String
    }
    +class NotificationDisplayer extends Thread{
      -state:PlayerState
      +NotificationDisplayer(state:PlayerState)
      +run():void
    }
    +class ControlDisplayer extends Thread{
      -state:PlayerState
      -playlist:Playlist
      -scanner:Scanner
      +ControlDisplayer(state PlayerState,playlist:Playlist)
      -showMenu():void
      +run():void
    }

  }
  package Utils{
    +class TimeFormatter{
      +{static}formatDuration(totalSeconds:int):String
      +{static}parseDuration(formatted:String):int
    }

  }
}
List <-- Music
Objects <.. Music
Collections <.. Music
Music <-- Playlist
ArrayList <-- Playlist
List <-- Playlist
Objects <.. Playlist
Collections <.. Playlist
PlayerState <-- MusicPlayer
PlayerState <-- LyricDisplayer
PlayerState <-- NotificationDisplayer
PlayerState <-- ControlDisplayer
Music <.. NotificationDisplayer
Music <-- PlayerState
Playlist <-- PlayerState
State +-- PlayerState
Objects <.. PlayerState
TimeFormatter <.. MusicPlayer
Music <.. MusicPlayer
TimeFormatter <.. LyricDisplayer
List <.. LyricDisplayer
Scanner <-- ControlDisplayer
Playlist <-- ControlDisplayer
Music <.. ControlDisplayer
Playlist <.. Main
PlayerState <.. Main
MusicPlayer <.. Main
LyricDisplayer <.. Main
NotificationDisplayer <.. Main
ControlDisplayer <.. Main
ArrayList <.. Main
List <.. Main
/'
-ini program pemutar musik multithreading
-tujuan program adalah implementasi thread maka user bisa input kapanpun walaupun program sedang menjalankan kegiatan lain
-kontrol untuk memberikan user pilihan pemutar musik berupa pause, next, resume, stop, show playlist, previous, choice music by-n, quit 
-kontrol muncul sekali saja di awal
-pilihan stop mengulang timer ke 0 lagi, lirik terdampak
-next dan previous itu berganti playlist
-notifikasi akan menampilkan hal yang berhubungan dengan status musik setiap menit meskipun user lagi menghentikan lagu dan program belum dimatikan
-kontrol tetap thread karena menunggu input user walaupun thread lain jalan
  '/
@enduml
