@startuml 
title WhatLyric
package WhatLyric{
  +class WhatLyric.Main{
    +{static}main(args:String[]):void
    -{static}createPlaylist():Playlist
    -{static}createLirikTerimaKasih():List<String>
    -{static}createLirikKicauMania():List<String>
    -{static}createLirikNoBatidao():List<String>
  }
  package Model{
    +class Music{
      -{final}title:String
      -{final}artist:String
      -{final}durationSeconds:int
      -{final}lyrics:List<String>
      +Music(title:String,artist:String,durationSeconds:int,lyrics:List<String>)
      +getTitle():String
      +getArtist():String
      +getDurationSeconds():int
      +getFormattedDuration():String
      +addLyricLine(lyricLine:String):void
      getLyryics():List<String>
      +getLyricsPreview():String
      +toString():String
    }
    +class Playlist{
      -{final}name:String
      -{final}tracks:List<Music>
      -currentTrackIndex:int
      +Playlist(name:String)
      +Playlist(tracks:List<Music>)
      +getName():String
      +addTrack(music:Music):void
      +removeTrack(music:Music):boolean
      +getTrackCount():int
      +getTracks():List<Music>
      +getCurrentTrack():Music
      +nextTrack():Music
      +previousTrack():Music
      +selectTrack(index:int):Music
      +getTotalDurationSeconds():int
      +getFormattedTotalDuration():String
      +toString():String
    }
  }
  package Resource{
    +class PlayerState{

    }
  }
  package Thread{
    +class MusicPlayer extends Thread{

    }
    +class LyricDisplayer extends Thread{

    }
    +class NotificationDisplayer extends Thread{

    }
    +class ControlDisplayer extends Thread{

    }

  }
  package Utils{
    +class TimeFormatter{

    }

  }
}
Music <-- Playlist
ArrayList <-- Playlist
List <-- Playlist
PlayerState <-- MusicPlayer
PlayerState <-- LyricDisplayer
PlayerState <-- NotificationDisplayer
PlayerState <-- ControlDisplayer
Music <.. NotificationDisplayer
Music <-- PlayerState
Playlist <-- PlayerState
TimeFormatter <.. MusicPlayer
Music <.. MusicPlayer
TimeFormatter <.. LyricDisplayer
Scanner <.. ControlDisplayer
TimeFormatter <.. ControlDisplayer
Playlist <.. Main
PlayerState <.. Main
MusicPlayer <.. Main
LyricDisplayer <.. Main
NotificationDisplayer <.. Main
ControlDisplayer <.. Main
ArrayList <.. Main
List <.. Main
/'
-ini program pemutar musik multithreading
-tujuan program adalah implementasi thread maka user bisa input kapanpun walaupun program sedang menjalankan kegiatan lain
-kontrol untuk memberikan user pilihan pemutar musik berupa pause, next, resume, stop, show playlist, previous, choice music by-n, quit 
-kontrol muncul sekali saja di awal
-pilihan stop mengulang timer ke 0 lagi, lirik terdampak
-next dan previous itu berganti playlist
-notifikasi akan menampilkan hal yang berhubungan dengan status musik setiap menit meskipun user lagi menghentikan lagu dan program belum dimatikan
-kontrol tetap thread karena menunggu input user walaupun thread lain jalan
  '/
@enduml
